const httpResponseCode = Object.freeze({ 
    HTTP_RESPONSE_OK : 200,
    HTTP_RESPONSE_OK_MULTI_STATUS : 207,
    HTTP_RESPONSE_NOCONTENT : 204,
    HTTP_RESPONSE_BAD_REQUEST : 400,
    HTTP_RESPONSE_INTERNAL_SERVER_ERROR : 500,
    HTTP_RESPONSE_FORBIDDEN : 403,
    HTTP_RESPONSE_NOT_FOUND : 404,
    HTTP_RESPONSE_UNAUTHORIZED: 401,
    HTTP_RESPONSE_CONFLICT: 409,
    HTTP_RESPONSE_ : 0,
});
module.exports = { httpResponseCode };
